export type SlideInterface = {
  id: number;
  slideType: string;
  slideText: string;
  additionalInfo: number;
  demographic?: Record<string, string>;
};

const SlideIDs = [1, 2, 3, 4, 5];

type SlideID = typeof SlideIDs[number];

const Slides: { [key in SlideID]: SlideInterface } = {
  1: {
    id: 1,
    slideText: "Auswahl Versuchsbedingung",
    slideType: "select",
    additionalInfo: 0,
  },
  2: {
    id: 2,
    slideText: "Eingabe Versuchspersonennummer",
    slideType: "Vpn",
    additionalInfo: 0,
  },
  3: { id: 3, slideText: "", slideType: "Code", additionalInfo: 0 },
  4: {
    id: 4,
    slideText:
      "Herzlich Willkommen! Schön, dass Du an dieser Studie teilnimmst.Zum Starten der Studie klicke bitte auf „Weiter“.",
    slideType: "Willkommen",
    additionalInfo: 0,
  },
  5: {
    id: 5,
    slideText:
      "Vielen Dank, dass Du an unserer Studie teilnimmst. Im Folgenden wirst Du verschiedene Aufgaben bearbeiten. \n \n \nBitte befolge stets die Anweisungen, die Dir auf den einzelnen Seiten gegeben werden. Für die vollständige Teilnahme an dieser Studie erhältst du eine Aufwandsentschädigung in Höhe von 10 Euro. Das Geld wird Dir nach erfolgreichem Abschluss der Studie per Überweisung ausgezahlt. Hierzu benötigen wir Deine Kontodaten, die Du nach dem Bearbeiten der Studie angeben musst. Die Daten werden nach Beendigung der Studie anonymisiert und ausschließlich zu forschungsinternen Zwecken von den Mitarbeiter*innen der Arbeitsgruppe „Pädagogische Intervention, Evaluation und Implementation“ der Ruhr-Universität Bochum gespeichert und verwendet. Du kannst der Speicherung und Verwendung Deiner Daten nachträglich widersprechen, musst dann jedoch die Aufwandsentschädigung zurückzahlen. Bitte beachte, dass die Löschung Deiner Daten nur so lange erfolgen kann, wie diese nicht anonymisiert wurden. \n \nBitte beachte, dass Du die Aufwandsentschädigung nur erhältst, wenn Du die Studie vollständig und entsprechend der Anweisungen bearbeitest. Das bedeutet, wenn Du einzelne Seiten z. B. ohne ernsthafte Bearbeitung „durchklickst“, dann können wir das in Deinen Daten sehen und können Dir die Aufwandsentschädigung für Deine Teilnahme nicht auszahlen. Die Teilnahme an dieser Studie ist freiwillig und kann jederzeit ohne negative Konsequenzen abgebrochen werden kann. \n \nWenn Du alles aufmerksam gelesen hast, klicke auf „Weiter“ und starte damit Deine Teilnahme an der Studie. \n \nKlicke nur auf „Weiter“, wenn Du mit den Teilnahmebedingungen einverstanden bist.",
    slideType: "Intro",
    additionalInfo: 0,
  },
  6: {
    id: 6,
    slideText:
      "Fülle bitte zunächst die folgenden Angaben zu Deiner Person aus. Klicke nach der Eingabe bitte auf „Weiter“.",
    slideType: "demographisch",
    additionalInfo: 0,
  },
  7: {
    id: 7,
    slideText:
      "Nun möchten wir Dich bitten, anzugeben, inwiefern die folgenden Aussagen auf Dich persönlich zutreffen. Es gibt keine richtigen oder falschen Antworten. Klicke auf „Weiter“, um zur nächsten Seite zu gelangen.",
    slideType: "demographisch_intro",
    additionalInfo: 0,
  },
  8: { id: 8, slideText: "", slideType: "Nachangaben_1_5", additionalInfo: 0 },
  9: { id: 9, slideText: "", slideType: "NachAngaben_6_11", additionalInfo: 0 },
  10: {
    id: 10,
    slideText: "",
    slideType: "Nachangaben_12_17",
    additionalInfo: 0,
  },
  11: {
    id: 11,
    slideText: "",
    slideType: "Nachangaben_18_22",
    additionalInfo: 0,
  },
  12: { id: 12, slideText: "", slideType: "Konzept_Intro", additionalInfo: 0 },
  13: {
    id: 13,
    slideText: "",
    slideType: "Konzept_Attribution",
    additionalInfo: 0,
  },
  14: { id: 14, slideText: "", slideType: "Konzept_SN", additionalInfo: 0 },
  15: {
    id: 15,
    slideText: "",
    slideType: "Konzept_Konsens",
    additionalInfo: 0,
  },
  16: {
    id: 16,
    slideText: "",
    slideType: "Konzept_Konsistenz",
    additionalInfo: 0,
  },
  17: {
    id: 17,
    slideText: "",
    slideType: "Konzept_Distinktheit",
    additionalInfo: 0,
  },
  18: { id: 18, slideText: "", slideType: "Konzept_FA", additionalInfo: 0 },
  19: { id: 19, slideText: "", slideType: "Konzept_SV", additionalInfo: 0 },
  20: { id: 20, slideText: "", slideType: "Konzept_GWG", additionalInfo: 0 },
  21: { id: 21, slideText: "", slideType: "Text_Intro", additionalInfo: 0 },
  22: { id: 22, slideText: "", slideType: "Text_Text", additionalInfo: 0 },
  23: {
    id: 23,
    slideText: "",
    slideType: "Definition_Intro",
    additionalInfo: 0,
  },
  24: {
    id: 24,
    slideText: "",
    slideType: "Definition_Attribution",
    additionalInfo: 0,
  },
  25: { id: 25, slideText: "", slideType: "Definition_SN", additionalInfo: 0 },
  26: {
    id: 26,
    slideText: "",
    slideType: "Definition_Konsens",
    additionalInfo: 0,
  },
  27: {
    id: 27,
    slideText: "",
    slideType: "Definition_Konsistenz",
    additionalInfo: 0,
  },
  28: {
    id: 28,
    slideText: "",
    slideType: "Definition_Distinktheit",
    additionalInfo: 0,
  },
  29: { id: 29, slideText: "", slideType: "Definition_FA", additionalInfo: 0 },
  30: { id: 30, slideText: "", slideType: "Definition_SV", additionalInfo: 0 },
  31: { id: 31, slideText: "", slideType: "Definition_GWG", additionalInfo: 0 },
  32: { id: 32, slideText: "", slideType: "Beispiel_Intro", additionalInfo: 0 },
  33: {
    id: 33,
    slideText: "",
    slideType: "Beispiel_Attribution0",
    additionalInfo: 0,
  },
  34: {
    id: 34,
    slideText: "",
    slideType: "Beispiel_Attribution1",
    additionalInfo: 0,
  },
  35: {
    id: 35,
    slideText: "",
    slideType: "Beispiel_Attribution2",
    additionalInfo: 0,
  },
  36: {
    id: 36,
    slideText: "",
    slideType: "Attribution_g1_1",
    additionalInfo: 0,
  },
  37: {
    id: 37,
    slideText: "",
    slideType: "Attribution_g1_2",
    additionalInfo: 0,
  },
  38: {
    id: 38,
    slideText: "",
    slideType: "Beispiel_Attribution3",
    additionalInfo: 0,
  },
  39: {
    id: 39,
    slideText: "",
    slideType: "Beispiel_Attribution4",
    additionalInfo: 0,
  },
  40: { id: 40, slideText: "", slideType: "Beispiel_SN0", additionalInfo: 0 },
  41: { id: 41, slideText: "", slideType: "Beispiel_SN1", additionalInfo: 0 },
  42: { id: 42, slideText: "", slideType: "Beispiel_SN2", additionalInfo: 0 },
  43: { id: 43, slideText: "", slideType: "SN_g1_1", additionalInfo: 0 },
  44: { id: 44, slideText: "", slideType: "SN_g1_2", additionalInfo: 0 },
  45: { id: 45, slideText: "", slideType: "Beispiel_SN3", additionalInfo: 0 },
  46: { id: 46, slideText: "", slideType: "Beispiel_SN4", additionalInfo: 0 },
  47: {
    id: 47,
    slideText: "",
    slideType: "Beispiel_Konsens0",
    additionalInfo: 0,
  },
  48: {
    id: 48,
    slideText: "",
    slideType: "Beispiel_Konsens1",
    additionalInfo: 0,
  },
  49: {
    id: 49,
    slideText: "",
    slideType: "Beispiel_Konsens2",
    additionalInfo: 0,
  },
  50: { id: 50, slideText: "", slideType: "Konsens_g1_1", additionalInfo: 0 },
  51: { id: 51, slideText: "", slideType: "Konsens_g1_2", additionalInfo: 0 },
  52: {
    id: 52,
    slideText: "",
    slideType: "Beispiel_Konsens3",
    additionalInfo: 0,
  },
  53: {
    id: 53,
    slideText: "",
    slideType: "Beispiel_Konsens4",
    additionalInfo: 0,
  },
  54: {
    id: 54,
    slideText: "",
    slideType: "Beispiel_Konsistenz0",
    additionalInfo: 0,
  },
  55: {
    id: 55,
    slideText: "",
    slideType: "Beispiel_Konsistenz1",
    additionalInfo: 0,
  },
  56: {
    id: 56,
    slideText: "",
    slideType: "Beispiel_Konsistenz2",
    additionalInfo: 0,
  },
  57: {
    id: 57,
    slideText: "",
    slideType: "Konsistenz_g1_1",
    additionalInfo: 0,
  },
  58: {
    id: 58,
    slideText: "",
    slideType: "Konsistenz_g1_2",
    additionalInfo: 0,
  },
  59: {
    id: 59,
    slideText: "",
    slideType: "Beispiel_Konsistenz3",
    additionalInfo: 0,
  },
  60: {
    id: 60,
    slideText: "",
    slideType: "Beispiel_Konsistenz4",
    additionalInfo: 0,
  },
  61: {
    id: 61,
    slideText: "",
    slideType: "Beispiel_Distinktheit0",
    additionalInfo: 0,
  },
  62: {
    id: 62,
    slideText: "",
    slideType: "Beispiel_Distinktheit1",
    additionalInfo: 0,
  },
  63: {
    id: 63,
    slideText: "",
    slideType: "Beispiel_Distinktheit2",
    additionalInfo: 0,
  },
  64: {
    id: 64,
    slideText: "",
    slideType: "Distinktheit_g1_1",
    additionalInfo: 0,
  },
  65: {
    id: 65,
    slideText: "",
    slideType: "Distinktheit_g1_2",
    additionalInfo: 0,
  },
  66: {
    id: 66,
    slideText: "",
    slideType: "Beispiel_Distinktheit3",
    additionalInfo: 0,
  },
  67: {
    id: 67,
    slideText: "",
    slideType: "Beispiel_Distinktheit4",
    additionalInfo: 0,
  },
  68: { id: 68, slideText: "", slideType: "Beispiel_FA0", additionalInfo: 0 },
  69: { id: 69, slideText: "", slideType: "Beispiel_FA1", additionalInfo: 0 },
  70: { id: 70, slideText: "", slideType: "Beispiel_FA2", additionalInfo: 0 },
  71: { id: 71, slideText: "", slideType: "FA_g1_1", additionalInfo: 0 },
  72: { id: 72, slideText: "", slideType: "FA_g1_2", additionalInfo: 0 },
  73: { id: 73, slideText: "", slideType: "Beispiel_FA3", additionalInfo: 0 },
  74: { id: 74, slideText: "", slideType: "Beispiel_FA4", additionalInfo: 0 },
  75: { id: 75, slideText: "", slideType: "Beispiel_SV0", additionalInfo: 0 },
  76: { id: 76, slideText: "", slideType: "Beispiel_SV1", additionalInfo: 0 },
  77: { id: 77, slideText: "", slideType: "Beispiel_SV2", additionalInfo: 0 },
  78: { id: 78, slideText: "", slideType: "SV_g1_1", additionalInfo: 0 },
  79: { id: 79, slideText: "", slideType: "SV_g1_2", additionalInfo: 0 },
  80: { id: 80, slideText: "", slideType: "Beispiel_SV3", additionalInfo: 0 },
  81: { id: 81, slideText: "", slideType: "Beispiel_SV4", additionalInfo: 0 },
  82: { id: 82, slideText: "", slideType: "Beispiel_GWG0", additionalInfo: 0 },
  83: { id: 83, slideText: "", slideType: "Beispiel_GWG1", additionalInfo: 0 },
  84: { id: 84, slideText: "", slideType: "Beispiel_GWG2", additionalInfo: 0 },
  85: { id: 85, slideText: "", slideType: "GWG_g1_1", additionalInfo: 0 },
  86: { id: 86, slideText: "", slideType: "GWG_g1_2", additionalInfo: 0 },
  87: { id: 87, slideText: "", slideType: "Beispiel_GWG3", additionalInfo: 0 },
  88: { id: 88, slideText: "", slideType: "Beispiel_GWG4", additionalInfo: 0 },
  89: { id: 89, slideText: "", slideType: "Ende", additionalInfo: 0 },
};

export default Slides;

export const slidesMocK: { [key in SlideID]: SlideInterface } = {
  1: { id: 1, slideText: "", slideType: "select", additionalInfo: 0 },
  2: { id: 2, slideText: "", slideType: "Vpn", additionalInfo: 0 },
  3: { id: 3, slideText: "", slideType: "Code", additionalInfo: 0 },
  4: { id: 4, slideText: "", slideType: "Willkommen", additionalInfo: 0 },
  5: { id: 5, slideText: "", slideType: "Intro", additionalInfo: 0 },
  6: { id: 6, slideText: "", slideType: "demographisch", additionalInfo: 0 },
  7: {
    id: 7,
    slideText: "",
    slideType: "demographisch_intro",
    additionalInfo: 0,
  },
  8: { id: 8, slideText: "", slideType: "Nachangaben_1_5", additionalInfo: 0 },
  9: { id: 9, slideText: "", slideType: "NachAngaben_6_11", additionalInfo: 0 },
  10: {
    id: 10,
    slideText: "",
    slideType: "Nachangaben_12_17",
    additionalInfo: 0,
  },
  11: {
    id: 11,
    slideText: "",
    slideType: "Nachangaben_18_22",
    additionalInfo: 0,
  },
  12: { id: 12, slideText: "", slideType: "Konzept_Intro", additionalInfo: 0 },
  13: {
    id: 13,
    slideText: "",
    slideType: "Konzept_Attribution",
    additionalInfo: 0,
  },
  14: { id: 14, slideText: "", slideType: "Konzept_SN", additionalInfo: 0 },
  15: {
    id: 15,
    slideText: "",
    slideType: "Konzept_Konsens",
    additionalInfo: 0,
  },
  16: {
    id: 16,
    slideText: "",
    slideType: "Konzept_Konsistenz",
    additionalInfo: 0,
  },
  17: {
    id: 17,
    slideText: "",
    slideType: "Konzept_Distinktheit",
    additionalInfo: 0,
  },
  18: { id: 18, slideText: "", slideType: "Konzept_FA", additionalInfo: 0 },
  19: { id: 19, slideText: "", slideType: "Konzept_SV", additionalInfo: 0 },
  20: { id: 20, slideText: "", slideType: "Konzept_GWG", additionalInfo: 0 },
  21: { id: 21, slideText: "", slideType: "Text_Intro", additionalInfo: 0 },
  22: { id: 22, slideText: "", slideType: "Text_Text", additionalInfo: 0 },
  23: {
    id: 23,
    slideText: "",
    slideType: "Definition_Intro",
    additionalInfo: 0,
  },
  24: {
    id: 24,
    slideText: "",
    slideType: "Definition_Attribution",
    additionalInfo: 0,
  },
  25: { id: 25, slideText: "", slideType: "Definition_SN", additionalInfo: 0 },
  26: {
    id: 26,
    slideText: "",
    slideType: "Definition_Konsens",
    additionalInfo: 0,
  },
  27: {
    id: 27,
    slideText: "",
    slideType: "Definition_Konsistenz",
    additionalInfo: 0,
  },
  28: {
    id: 28,
    slideText: "",
    slideType: "Definition_Distinktheit",
    additionalInfo: 0,
  },
  29: { id: 29, slideText: "", slideType: "Definition_FA", additionalInfo: 0 },
  30: { id: 30, slideText: "", slideType: "Definition_SV", additionalInfo: 0 },
  31: { id: 31, slideText: "", slideType: "Definition_GWG", additionalInfo: 0 },
  32: { id: 32, slideText: "", slideType: "Beispiel_Intro", additionalInfo: 0 },
  33: {
    id: 33,
    slideText: "",
    slideType: "Beispiel_Attribution0",
    additionalInfo: 0,
  },
  34: {
    id: 34,
    slideText: "",
    slideType: "Beispiel_Attribution1",
    additionalInfo: 0,
  },
  35: {
    id: 35,
    slideText: "",
    slideType: "Beispiel_Attribution2",
    additionalInfo: 0,
  },
  36: {
    id: 36,
    slideText: "",
    slideType: "Attribution_g1_1",
    additionalInfo: 0,
  },
  37: {
    id: 37,
    slideText: "",
    slideType: "Attribution_g1_2",
    additionalInfo: 0,
  },
  38: {
    id: 38,
    slideText: "",
    slideType: "Beispiel_Attribution3",
    additionalInfo: 0,
  },
  39: {
    id: 39,
    slideText: "",
    slideType: "Beispiel_Attribution4",
    additionalInfo: 0,
  },
  40: { id: 40, slideText: "", slideType: "Beispiel_SN0", additionalInfo: 0 },
  41: { id: 41, slideText: "", slideType: "Beispiel_SN1", additionalInfo: 0 },
  42: { id: 42, slideText: "", slideType: "Beispiel_SN2", additionalInfo: 0 },
  43: { id: 43, slideText: "", slideType: "SN_g1_1", additionalInfo: 0 },
  44: { id: 44, slideText: "", slideType: "SN_g1_2", additionalInfo: 0 },
  45: { id: 45, slideText: "", slideType: "Beispiel_SN3", additionalInfo: 0 },
  46: { id: 46, slideText: "", slideType: "Beispiel_SN4", additionalInfo: 0 },
  47: {
    id: 47,
    slideText: "",
    slideType: "Beispiel_Konsens0",
    additionalInfo: 0,
  },
  48: {
    id: 48,
    slideText: "",
    slideType: "Beispiel_Konsens1",
    additionalInfo: 0,
  },
  49: {
    id: 49,
    slideText: "",
    slideType: "Beispiel_Konsens2",
    additionalInfo: 0,
  },
  50: { id: 50, slideText: "", slideType: "Konsens_g1_1", additionalInfo: 0 },
  51: { id: 51, slideText: "", slideType: "Konsens_g1_2", additionalInfo: 0 },
  52: {
    id: 52,
    slideText: "",
    slideType: "Beispiel_Konsens3",
    additionalInfo: 0,
  },
  53: {
    id: 53,
    slideText: "",
    slideType: "Beispiel_Konsens4",
    additionalInfo: 0,
  },
  54: {
    id: 54,
    slideText: "",
    slideType: "Beispiel_Konsistenz0",
    additionalInfo: 0,
  },
  55: {
    id: 55,
    slideText: "",
    slideType: "Beispiel_Konsistenz1",
    additionalInfo: 0,
  },
  56: {
    id: 56,
    slideText: "",
    slideType: "Beispiel_Konsistenz2",
    additionalInfo: 0,
  },
  57: {
    id: 57,
    slideText: "",
    slideType: "Konsistenz_g1_1",
    additionalInfo: 0,
  },
  58: {
    id: 58,
    slideText: "",
    slideType: "Konsistenz_g1_2",
    additionalInfo: 0,
  },
  59: {
    id: 59,
    slideText: "",
    slideType: "Beispiel_Konsistenz3",
    additionalInfo: 0,
  },
  60: {
    id: 60,
    slideText: "",
    slideType: "Beispiel_Konsistenz4",
    additionalInfo: 0,
  },
  61: {
    id: 61,
    slideText: "",
    slideType: "Beispiel_Distinktheit0",
    additionalInfo: 0,
  },
  62: {
    id: 62,
    slideText: "",
    slideType: "Beispiel_Distinktheit1",
    additionalInfo: 0,
  },
  63: {
    id: 63,
    slideText: "",
    slideType: "Beispiel_Distinktheit2",
    additionalInfo: 0,
  },
  64: {
    id: 64,
    slideText: "",
    slideType: "Distinktheit_g1_1",
    additionalInfo: 0,
  },
  65: {
    id: 65,
    slideText: "",
    slideType: "Distinktheit_g1_2",
    additionalInfo: 0,
  },
  66: {
    id: 66,
    slideText: "",
    slideType: "Beispiel_Distinktheit3",
    additionalInfo: 0,
  },
  67: {
    id: 67,
    slideText: "",
    slideType: "Beispiel_Distinktheit4",
    additionalInfo: 0,
  },
  68: { id: 68, slideText: "", slideType: "Beispiel_FA0", additionalInfo: 0 },
  69: { id: 69, slideText: "", slideType: "Beispiel_FA1", additionalInfo: 0 },
  70: { id: 70, slideText: "", slideType: "Beispiel_FA2", additionalInfo: 0 },
  71: { id: 71, slideText: "", slideType: "FA_g1_1", additionalInfo: 0 },
  72: { id: 72, slideText: "", slideType: "FA_g1_2", additionalInfo: 0 },
  73: { id: 73, slideText: "", slideType: "Beispiel_FA3", additionalInfo: 0 },
  74: { id: 74, slideText: "", slideType: "Beispiel_FA4", additionalInfo: 0 },
  75: { id: 75, slideText: "", slideType: "Beispiel_SV0", additionalInfo: 0 },
  76: { id: 76, slideText: "", slideType: "Beispiel_SV1", additionalInfo: 0 },
  77: { id: 77, slideText: "", slideType: "Beispiel_SV2", additionalInfo: 0 },
  78: { id: 78, slideText: "", slideType: "SV_g1_1", additionalInfo: 0 },
  79: { id: 79, slideText: "", slideType: "SV_g1_2", additionalInfo: 0 },
  80: { id: 80, slideText: "", slideType: "Beispiel_SV3", additionalInfo: 0 },
  81: { id: 81, slideText: "", slideType: "Beispiel_SV4", additionalInfo: 0 },
  82: { id: 82, slideText: "", slideType: "Beispiel_GWG0", additionalInfo: 0 },
  83: { id: 83, slideText: "", slideType: "Beispiel_GWG1", additionalInfo: 0 },
  84: { id: 84, slideText: "", slideType: "Beispiel_GWG2", additionalInfo: 0 },
  85: { id: 85, slideText: "", slideType: "GWG_g1_1", additionalInfo: 0 },
  86: { id: 86, slideText: "", slideType: "GWG_g1_2", additionalInfo: 0 },
  87: { id: 87, slideText: "", slideType: "Beispiel_GWG3", additionalInfo: 0 },
  88: { id: 88, slideText: "", slideType: "Beispiel_GWG4", additionalInfo: 0 },
  89: { id: 89, slideText: "", slideType: "Ende", additionalInfo: 0 },
};
